### ISSUE TITLE
Option to use main camera

### ISSUE THREAD

**Issue by dbrand666** [0xf104a/Mirror#14]
Teacher here.

This is an enhancement request.

I have a game that "hides" the answers in mirror writing. It would be handy to be able to use this app when I forget my mirror. 

I can use the front camera but it's awkward positioning the page between the phone and my eyes.

Would it be possible to add an option to switch cameras while keeping the mirroring?

If this is an easy addition.

**Comment by dbrand666** [comment]
See https://github.com/0xf104a/Mirror/pull/15

**Comment by 0xf104a** [comment]
Closed with #15
